name: lint
run-name: 'Lint workflow'

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 4 * * 1'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Black Link
        uses: psf/black@stable
